[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [executing] active: 
  vault-k8s/1 [executing] active: 
  vault-k8s/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  tls-certificates-requirer/0 [executing] active: Certificate relation is created
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model          Controller                Cloud/Region        Version  SLA          Timestamp
test-pki-v8wg  github-pr-d9e0a-microk8s  microk8s/localhost  3.6.6    unsupported  01:12:01Z

App                        Version  Status  Scale  Charm                      Channel        Rev  Address         Exposed  Message
self-signed-certificates            active      1  self-signed-certificates   1/stable       263  10.152.183.19   no       
tls-certificates-requirer           active      1  tls-certificates-requirer  latest/stable   93  10.152.183.77   no       Unit certificate is available
vault-k8s                           active      3  vault-k8s                                   0  10.152.183.222  no       

Unit                          Workload  Agent  Address      Ports  Message
self-signed-certificates/0*   active    idle   10.1.249.20         
tls-certificates-requirer/0*  active    idle   10.1.249.23         Unit certificate is available
vault-k8s/0*                  active    idle   10.1.249.17         
vault-k8s/1                   active    idle   10.1.249.26         
vault-k8s/2                   active    idle   10.1.249.25         

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-vault-k8s-0: 01:09:43 ERROR unit.vault-k8s/0.juju-log vault-peers:0: Error getting storage location for certs: ERROR invalid value "certs/0" for option -s: getting filesystem attachment info: filesystem attachment "0" on "unit vault-k8s/0" not provisioned

unit-vault-k8s-0: 01:09:45 ERROR unit.vault-k8s/0.juju-log Error getting storage location for certs: ERROR invalid value "certs/0" for option -s: getting filesystem attachment info: filesystem attachment "0" on "unit vault-k8s/0" not provisioned

unit-vault-k8s-0: 01:09:46 ERROR unit.vault-k8s/0.juju-log Error getting storage location for certs: ERROR invalid value "certs/0" for option -s: getting filesystem attachment info: filesystem attachment "0" on "unit vault-k8s/0" not provisioned

unit-vault-k8s-0: 01:09:49 ERROR unit.vault-k8s/0.juju-log Error getting storage location for certs: ERROR invalid value "certs/0" for option -s: getting filesystem attachment info: filesystem attachment "0" on "unit vault-k8s/0" not provisioned

unit-vault-k8s-0: 01:09:49 ERROR unit.vault-k8s/0.juju-log Error getting storage location for certs: ERROR invalid value "certs/0" for option -s: getting filesystem attachment info: filesystem attachment "0" on "unit vault-k8s/0" not provisioned

unit-vault-k8s-0: 01:09:51 ERROR unit.vault-k8s/0.juju-log Error getting storage location for certs: ERROR invalid value "certs/0" for option -s: getting filesystem attachment info: filesystem attachment "0" on "unit vault-k8s/0" not provisioned

unit-self-signed-certificates-0: 01:11:02 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 01:11:13 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 01:11:15 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 01:11:18 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 01:11:21 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 01:11:28 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 01:11:53 ERROR unit.self-signed-certificates/0.juju-log certificates:1: At least 1 matching relation ID not found with the relation name 'send-ca-cert'

[32mINFO    [0m pytest_operator.plugin:plugin.py:1049 Resetting model test-pki-v8wg...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications self-signed-certificates
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications tls-certificates-requirer
[32mINFO    [0m pytest_operator.plugin:plugin.py:1054 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...