{"uid":"52f6782e4be65a5","name":"test_given_application_is_deployed_when_pod_crashes_then_unit_recovers","fullName":"tests.integration.test_integration.TestVaultK8s#test_given_application_is_deployed_when_pod_crashes_then_unit_recovers","historyId":"f0638feda94066be89a1a88dc107e86f","time":{"start":1736979392126,"stop":1736979392126,"duration":0},"status":"broken","statusMessage":"juju.errors.JujuUnitError: Unit in error: vault-k8s/0","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 90, in pytest_runtest_setup\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 840, in pytest_runtest_setup\n    yield from self._runtest_for(item, \"setup\")\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 875, in pytest_runtest_setup\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 87, in pytest_runtest_setup\n    yield from thread_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 160, in pytest_runtest_setup\n    item.session._setupstate.setup(item)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 514, in setup\n    col.setup()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1630, in setup\n    self._request._fillfixtures()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 697, in _fillfixtures\n    item.funcargs[argname] = self.getfixturevalue(argname)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 532, in getfixturevalue\n    fixturedef = self._get_active_fixturedef(argname)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 617, in _get_active_fixturedef\n    fixturedef.execute(request=subrequest)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1047, in execute\n    fixturedef = request._get_active_fixturedef(argname)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 617, in _get_active_fixturedef\n    fixturedef.execute(request=subrequest)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1071, in execute\n    raise exc.with_traceback(exc_tb)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 323, in _async_fixture_wrapper\n    return event_loop.run_until_complete(setup())\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 320, in setup\n    res = await func(**_add_kwargs(func, kwargs, event_loop, request))\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/tests/integration/test_integration.py\", line 78, in deployed_vault\n    await ops_test.model.wait_for_idle(\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 3203, in wait_for_idle\n    _raise_for_status(errors, \"error\")\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 3094, in _raise_for_status\n    raise error_type(\njuju.errors.JujuUnitError: Unit in error: vault-k8s/0","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"tmp_path_factory","time":{"start":1736979313630,"stop":1736979313630,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"ops_test","time":{"start":1736979313630,"stop":1736979314128,"duration":498},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop","time":{"start":1736979313630,"stop":1736979313630,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"deployed_vault","time":{"start":1736979314128,"stop":1736979392119,"duration":77991},"status":"broken","statusMessage":"juju.errors.JujuUnitError: Unit in error: vault-k8s/0\n","statusTrace":"  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 323, in _async_fixture_wrapper\n    return event_loop.run_until_complete(setup())\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 320, in setup\n    res = await func(**_add_kwargs(func, kwargs, event_loop, request))\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/tests/integration/test_integration.py\", line 78, in deployed_vault\n    await ops_test.model.wait_for_idle(\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 3203, in wait_for_idle\n    _raise_for_status(errors, \"error\")\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 3094, in _raise_for_status\n    raise error_type(\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[{"name":"ops_test::finalizer","time":{"start":1736979392168,"stop":1736979395776,"duration":3608},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::2","time":{"start":1736979395777,"stop":1736979395777,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::_close_event_loop","time":{"start":1736979395777,"stop":1736979395777,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1736979395777,"stop":1736979395778,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_integration"},{"name":"subSuite","value":"TestVaultK8s"},{"name":"host","value":"github-runner"},{"name":"thread","value":"23382-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_integration"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":4,"skipped":1,"passed":11,"unknown":0,"total":16},"items":[{"uid":"8c1a6fd51812e35","reportUrl":"https://canonical.github.io/vault-k8s-operator/2718//#testresult/8c1a6fd51812e35","status":"broken","statusDetails":"juju.errors.JujuUnitError: Unit in error: vault-k8s/0","time":{"start":1736952815958,"stop":1736952815958,"duration":0}},{"uid":"113879c8e4828c05","reportUrl":"https://canonical.github.io/vault-k8s-operator/2718//#testresult/113879c8e4828c05","status":"broken","statusDetails":"juju.errors.JujuUnitError: Unit in error: vault-k8s/0","time":{"start":1736948961779,"stop":1736948961779,"duration":0}},{"uid":"4c623746de401347","reportUrl":"https://canonical.github.io/vault-k8s-operator/2717//#testresult/4c623746de401347","status":"passed","time":{"start":1736898822831,"stop":1736898884341,"duration":61510}},{"uid":"56ee4435016b0150","reportUrl":"https://canonical.github.io/vault-k8s-operator/2718//#testresult/56ee4435016b0150","status":"broken","statusDetails":"juju.errors.JujuUnitError: Unit in error: vault-k8s/0","time":{"start":1736899938786,"stop":1736899938786,"duration":0}},{"uid":"82b063982ab9fbc","reportUrl":"https://canonical.github.io/vault-k8s-operator/2716//#testresult/82b063982ab9fbc","status":"passed","time":{"start":1736894394765,"stop":1736894467713,"duration":72948}},{"uid":"9f229528d4165752","reportUrl":"https://canonical.github.io/vault-k8s-operator/2715//#testresult/9f229528d4165752","status":"passed","time":{"start":1736892606206,"stop":1736892670159,"duration":63953}},{"uid":"9d97b4ba8515e61b","reportUrl":"https://canonical.github.io/vault-k8s-operator/2714//#testresult/9d97b4ba8515e61b","status":"passed","time":{"start":1736863771295,"stop":1736863832307,"duration":61012}},{"uid":"6835e008166b576d","reportUrl":"https://canonical.github.io/vault-k8s-operator/2713//#testresult/6835e008166b576d","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1736864860326,"stop":1736864860326,"duration":0}},{"uid":"142363a8ae697be3","reportUrl":"https://canonical.github.io/vault-k8s-operator/2711//#testresult/142363a8ae697be3","status":"passed","time":{"start":1736854056155,"stop":1736854118552,"duration":62397}},{"uid":"cc7b67de1f825522","reportUrl":"https://canonical.github.io/vault-k8s-operator/2710//#testresult/cc7b67de1f825522","status":"passed","time":{"start":1736806894007,"stop":1736806955399,"duration":61392}},{"uid":"74223dd5e4526e96","reportUrl":"https://canonical.github.io/vault-k8s-operator/2709//#testresult/74223dd5e4526e96","status":"passed","time":{"start":1736802712910,"stop":1736802774093,"duration":61183}},{"uid":"d5f8e0fc86bceb31","reportUrl":"https://canonical.github.io/vault-k8s-operator/2708//#testresult/d5f8e0fc86bceb31","status":"passed","time":{"start":1736799206853,"stop":1736799268172,"duration":61319}},{"uid":"66c1d49d761e77af","reportUrl":"https://canonical.github.io/vault-k8s-operator/2707//#testresult/66c1d49d761e77af","status":"passed","time":{"start":1736797329991,"stop":1736797391468,"duration":61477}},{"uid":"32650bc94aff9a6d","reportUrl":"https://canonical.github.io/vault-k8s-operator/2689//#testresult/32650bc94aff9a6d","status":"passed","time":{"start":1736782409266,"stop":1736782473253,"duration":63987}},{"uid":"6570c110aa73580","reportUrl":"https://canonical.github.io/vault-k8s-operator/2689//#testresult/6570c110aa73580","status":"passed","time":{"start":1736775326223,"stop":1736775387835,"duration":61612}}]},"tags":["asyncio","abort_on_fail"]},"source":"52f6782e4be65a5.json","parameterValues":[]}